### ISSUE TITLE
Update Navigation Bar properties in App Delegate

### ISSUE THREAD

**Issue by MiguelTepale** [MiguelTepale/iOS-Studies#2]
This includes the navigation bar color and font type. In addition, you also can set the attributes for the Navigation Bar title text as well.

**Comment by nitisha-neuroleap** [comment]
I finally figured out the syntax to change the properties of a UIButton, but it does not change anything in the .xib file. I have a picture of my current code below. 

I also tried to set a variable to UIButton() and change the properties from the variable. Only the setTitleColor() works with this method.  

<img width="341" alt="Screen Shot 2020-05-26 at 10 29 50 PM" src="https://user-images.githubusercontent.com/65615448/82971331-6bc6dd00-9fa0-11ea-87df-79fa198cd2ad.png">

**Comment by MiguelTepale** [comment]
Hi Nitisha, good work on starting the iOS Studies app. I have to apologize, I should have thought the title through a bit more. Configuring the UIButton in the App Delegate is a good idea but should be avoided since UI work should be done either in Storyboards or XIBs. This will help to contain the UI to those files and avoid from code being in another file (App Delegate). Obviously, that's not your fault but mine. Thus, I will revise this title. Remove the code you have written and let's try again. Please comment if you have further questions.

**Comment by MiguelTepale** [comment]
Also, please review "branching in git" and branch off the master branch while working on the App Delegate.

**Comment by MiguelTepale** [comment]
When I say properties, this includes the navigation bar color and font type. In addition, you also can set the attributes for the Navigation Bar title text as well.
