### ISSUE TITLE
UIButtons need to resize properly for all devices

### ISSUE THREAD

**Issue by MiguelTepale** [MiguelTepale/iOS-Studies#5]
I tested your view on other devices and this is what it looked like on iPhone 11:

![Simulator Screen Shot - iPhone 11 - 2020-05-27 at 19 16 38](https://user-images.githubusercontent.com/16193288/83108906-78c1fa00-a08e-11ea-8a70-7b33c6a46718.png)
This would be a good opportunity for you to learn Auto Layout. Please remove all "button insets" and "padding" in the MainViewController.swift. Perform all UI work in MainViewController.xib file. Make sure to branch off while you develop this feature.

**Comment by nitisha-neuroleap** [comment]
Should the buttons be of the same size or should the constraints remain constant for all screen sizes?

**Comment by MiguelTepale** [comment]
The buttons should be the same size through out all devices. Constraints is a whole different ball game. Yes, some constraints will be the same but other constraints might conflict with one another during rendering. It'll be up to you to resolve those conflicts when they occur.

**Comment by MiguelTepale** [comment]
Completed with PR #6
